DATA_DIR = 'data/'

MASCOT_BY_ABREV = {
    'NE': 'Patriots',
    'NYJ': 'Jets',
    'MIA': 'Dolphins',
    'BUF': 'Buffalo',
    'PIT': 'Steelers',
    'BAL': 'Ravens',
    'CLE': 'Browns',
    'CIN': 'Bengals',
    'HOU': 'Texans',
    'IND': 'Colts',
    'JAC': 'Jaguars',
    'TEN': 'Titans',
    'DEN': 'Broncos',
    'KC': 'Chiefs',
    'SD': 'Chargers',
    'OAK': 'Raiders',
    'DAL': 'Cowboys',
    'WAS': 'Redskins',
    'NYG': 'Giants',
    'PHI': 'Eagles',
    'MIN': 'Vikings',
    'GB': 'Packers',
    'DET': 'Lions',
    'CHI': 'Bears',
    'NO': 'Saints',
    'TB': 'Buccaneers',
    'ATL': 'Falcons',
    'CAR': 'Panthers',
    'SF': '49ers',
    'SEA': 'Seahawks',
    'ARI': 'Cardinals',
    'LA': 'Rams',
}

ABREV_BY_MASCOT = {
    'Patriots': 'NE',
    'Jets': 'NYJ',
    'Dolphins': 'MIA',
    'Bills': 'BUF',
    'Steelers': 'PIT',
    'Ravens': 'BAL',
    'Browns': 'CLE',
    'Bengals': 'CIN',
    'Texans': 'HOU',
    'Colts': 'IND',
    'Jaguars': 'JAC',
    'Titans': 'TEN',
    'Broncos': 'DEN',
    'Chiefs': 'KC',
    'Chargers': 'SD',
    'Raiders': 'OAK',
    'Cowboys': 'DAL',
    'Redskins': 'WAS',
    'Giants': 'NYG',
    'Eagles': 'PHI',
    'Vikings': 'MIN',
    'Packers': 'GB',
    'Lions': 'DET',
    'Bears': 'CHI',
    'Saints': 'NO',
    'Buccaneers': 'TB',
    'Falcons': 'ATL',
    'Panthers': 'CAR',
    '49ers': 'SF',
    'Seahawks': 'SEA',
    'Cardinals': 'ARI',
    'Rams': 'LA',
}


teams = [
    ['ARI', 'Arizona', 'Cardinals', 'Arizona Cardinals'],
    ['ATL', 'Atlanta', 'Falcons', 'Atlanta Falcons'],
    ['BAL', 'Baltimore', 'Ravens', 'Baltimore Ravens'],
    ['BUF', 'Buffalo', 'Bills', 'Buffalo Bills'],
    ['CAR', 'Carolina', 'Panthers', 'Carolina Panthers'],
    ['CHI', 'Chicago', 'Bears', 'Chicago Bears'],
    ['CIN', 'Cincinnati', 'Bengals', 'Cincinnati Bengals'],
    ['CLE', 'Cleveland', 'Browns', 'Cleveland Browns'],
    ['DAL', 'Dallas', 'Cowboys', 'Dallas Cowboys'],
    ['DEN', 'Denver', 'Broncos', 'Denver Broncos'],
    ['DET', 'Detroit', 'Lions', 'Detroit Lions'],
    ['GB', 'Green Bay', 'Packers', 'Green Bay Packers', 'G.B.', 'GNB'],
    ['HOU', 'Houston', 'Texans', 'Houston Texans'],
    ['IND', 'Indianapolis', 'Colts', 'Indianapolis Colts'],
    ['JAC', 'Jacksonville', 'Jaguars', 'Jacksonville Jaguars', 'JAX'],
    ['KC', 'Kansas City', 'Chiefs', 'Kansas City Chiefs', 'K.C.', 'KAN'],
    ['MIA', 'Miami', 'Dolphins', 'Miami Dolphins'],
    ['MIN', 'Minnesota', 'Vikings', 'Minnesota Vikings'],
    ['NE', 'New England', 'Patriots', 'New England Patriots', 'N.E.', 'NWE'],
    ['NO', 'New Orleans', 'Saints', 'New Orleans Saints', 'N.O.', 'NOR'],
    ['NYG', 'Giants', 'New York Giants', 'N.Y.G.'],
    ['NYJ', 'Jets', 'New York Jets', 'N.Y.J.'],
    ['OAK', 'Oakland', 'Raiders', 'Oakland Raiders'],
    ['PHI', 'Philadelphia', 'Eagles', 'Philadelphia Eagles'],
    ['PIT', 'Pittsburgh', 'Steelers', 'Pittsburgh Steelers'],
    ['SD', 'San Diego', 'Chargers', 'San Diego Chargers', 'S.D.', 'SDG'],
    ['SEA', 'Seattle', 'Seahawks', 'Seattle Seahawks'],
    ['SF', 'San Francisco', '49ers', 'San Francisco 49ers', 'S.F.', 'SFO'],
    ['LA', 'St. Louis', 'Rams', 'St. Louis Rams', 'S.T.L.'],
    ['TB', 'Tampa Bay', 'Buccaneers', 'Tampa Bay Buccaneers', 'T.B.', 'TAM'],
    ['TEN', 'Tennessee', 'Titans', 'Tennessee Titans'],
    ['WAS', 'Washington', 'Redskins', 'Washington Redskins', 'WSH'],
]
