NFL_WEEKLY_MAX_GAME_COUNT = 16

ABREV_BY_MASCOT = {
    'Patriots': 'NE',
    'Jets': 'NYJ',
    'Dolphins': 'MIA',
    'Bills': 'BUF',
    'Steelers': 'PIT',
    'Ravens': 'BAL',
    'Browns': 'CLE',
    'Bengals': 'CIN',
    'Texans': 'HOU',
    'Colts': 'IND',
    'Jaguars': 'JAC',
    'Titans': 'TEN',
    'Broncos': 'DEN',
    'Chiefs': 'KC',
    'Chargers': 'SD',
    'Raiders': 'OAK',
    'Cowboys': 'DAL',
    'Redskins': 'WAS',
    'Giants': 'NYG',
    'Eagles': 'PHI',
    'Vikings': 'MIN',
    'Packers': 'GB',
    'Lions': 'DET',
    'Bears': 'CHI',
    'Saints': 'NO',
    'Buccaneers': 'TB',
    'Falcons': 'ATL',
    'Panthers': 'CAR',
    '49ers': 'SF',
    'Seahawks': 'SEA',
    'Cardinals': 'ARI',
    'Rams': 'LA',
}
DATA_DIR = 'data/'
